### ISSUE TITLE
Potential breakage with geckodriver 0.27.0

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/firefox-feedstock#25]
Over on https://github.com/conda-forge/geckodriver-feedstock/pull/11, I've run into a snag testing with `downstream` on osx vs `firefox=79` ([build log](
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=190704&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1641)).

Still investigating...

**Comment by birdsarah** [comment]
Saw your note on the feedstock page. Some probably obvious thoughts in case they're useful:

* Looking at the test code (https://github.com/conda-forge/firefox-feedstock/blob/master/recipe/run_test.py#L48-L55) the error is because the `about:license` or the driver isn't loading - it's the except block error, not the page content.
* I've confirmed on ff79 on osx that `about:license` still exists and has the looked for text
* I've done the following test on OSX:
 - created conda env with ff79
 - conda installed selenium
 - manually downloaded latest geckodriver release
 - ran the catalina notarization work around (https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html) (`% xattr -r -d com.apple.quarantine geckodriver`)
 - been able to run a simple webdriver test that checks `about:license` and `about:support`

All this points to me that this package is working ok. And, unfortunately there's a problem with the geckodriver build.

Really appreciate your work on the geckodriver feedstock. If I can do anything to help. Let me know.

**Comment by bollwyvl** [comment]
Great! If it's osx related, I'm working blindly, so these might help. My
next step (probably on the weekend) is to get some better debug info
printed, and compare against some older versions.

If it really just "is this way" on osx then... I dunno.

**Comment by bollwyvl** [comment]
> And, unfortunately there's a problem with the geckodriver build.

Can you elaborate on this? As in, you are not able to build this geckodriver locally on OSX? Or 0.26.0 _also_ doesn't work?

I'm going to read the page, and might answer these myself:
- does the notarization hack have to be run as `root`? 
- can we do it during the `geckodriver` build? 
- can we add a script the user must run before they use it?

**Comment by bollwyvl** [comment]
> does the notarization hack have to be run as root?

Probably not?

> can we do it during the geckodriver build?

Almost certainly not.

> can we add a script the user must run before they use it?

this might have to be the way. not sure how one would handle the dialog in a headless setting, sounds like it might just block with no feedback...

**Comment by birdsarah** [comment]
> Can you elaborate on this? As in, you are not able to build this geckodriver locally on OSX? 

I have not tried building locally on OSX. I can if that would be helpful.

> Or 0.26.0 also doesn't work?

I am pretty confident 0.26.0 works from the conda package because we have a number of folks doing openwpm work on OSX who would have been using this package. I can test either the conda package or the direct download if it would be useful.

> does the notarization hack have to be run as root?

I ran it as my standard user

> can we do it during the geckodriver build?

I would guess not, I am guessing this is about the machine authorizing and the point is the software can't authorize itself....that said if we can package firefox as a binary with conda, without this authorization stuff, why not geckodriver - I have no idea about this stuff. My day-to-day machine is Linux. But I can easily test on OSX.

> can we add a script the user must run before they use it?

Presumably. In the case of one's own work I think it's okay to have to run this. Seems like bad form to somehow package up this kind of an action and have a package run a script that is designed to protect users...hmmmm....Is there anyway the conda package can do a "local build" on `conda install` that would then negate this need...just brainstorming...I don't know anything about this catalina problem.

----

Let me know what I can try that might be useful. I'm not familiar with building crates, but if you point me to a docs page, I can get there.

**Comment by bollwyvl** [comment]
The underlying issue is that `0.27.0` actually verifies if the `firefox_binary` you give it is _actually a firefox binary_, and doesn't accept the wrapper shell script we employ here. Giving it the _real_ firefox does the trick. So there may be some issues to update in the tests once `0.27.0` lands and starts coming in... will have to see on subsequent releases. 

I guess let's keep this open until at least the next release, unless some other other things come up that need correction.

**Comment by bollwyvl** [comment]
this was fixed upstream:
https://github.com/mozilla/geckodriver/releases/tag/v0.28.0

Nothing much we can do about 0.27.0, but the compatibility window did not change for 0.28.0, so there's very little reason not to switch. pleas re-open if issues appear.
